### ISSUE TITLE
feature request: ability to link directly to bot source

### ISSUE THREAD

**Issue by alien-sunset** [olafmoriarty/blue-bots-done-quick#7]
would be neat to be able to link directly to my bot's source, say in a post or from it's profile, so that people viewing the bot on bluesky can click through to see, rather than going to the blue bots site and trying to find via scrolling.

**Comment by olafmoriarty** [comment]
Agreed.

**Comment by olafmoriarty** [comment]
**TODO:**

- [ ] Add react router to the project
- [ ] Add backend endpoint (based on backend/list.php?) that returns info and source for a single bot
- [ ] Create single bot page component in React
- [ ] Set up route to single bot page
- [ ] Create an "All bots" index page to display all bots, not just the last ten / most popular ten, with links to single bot pages
